//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageFiles
    {
        public ImageFiles()
        {
            this.SliderImages = new HashSet<SliderImages>();
            this.Gallery = new HashSet<Gallery>();
            this.TreatmentDetails = new HashSet<TreatmentDetails>();
        }
    
        public string FileGuid { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public decimal Size { get; set; }
        public string ContentType { get; set; }
    
        public virtual ICollection<SliderImages> SliderImages { get; set; }
        public virtual ICollection<Gallery> Gallery { get; set; }
        public virtual ICollection<TreatmentDetails> TreatmentDetails { get; set; }
    }
}
