//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderImages
    {
        public int SliderImageId { get; set; }
        public string CaptionHeading { get; set; }
        public string CaptionDetails { get; set; }
        public string ImageId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ImageFiles ImageFiles { get; set; }
    }
}
