//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatments
    {
        public Treatments()
        {
            this.TreatmentDetails = new HashSet<TreatmentDetails>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int TreatmentTypeId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual TreatmentTypes TreatmentTypes { get; set; }
        public virtual ICollection<TreatmentDetails> TreatmentDetails { get; set; }
    }
}
