//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VedicaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentTypes
    {
        public TreatmentTypes()
        {
            this.Treatments = new HashSet<Treatments>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Treatments> Treatments { get; set; }
    }
}
